### ISSUE TITLE
Duplicate repo's - potentially merge?

### ISSUE THREAD

**Issue by rowanwins** [tchannel/turf-polygon-within#1]
Gday @tcql 

It seems like we may have crossed paths a bit on some repos, eg I made my own versions of [overlaps](https://github.com/rowanwins/turf-overlap) and [polygon-within](https://github.com/rowanwins/turf-completelyWithin)

However we also approach things in different ways 
- My modules are based on loops for dealing with collections, your modules deal with a single features.
- Mine return feature collections, yours return true or false
- Our algorithms are a bit different
  - I do checks on whether the bounding boxes overlap first before proceeding to line intersect checkes (from my testing this really helped speed things up on large datasets)

Is it worth attempting to combine our approaches/modules? I think the return statements could perhaps be worked in as a param (eg the user decides whether they want bool or features). Could we work in dealing with collections vs individual features?

I"d love to see these modules make it into turf as I think they're quite valuable.

Any ideas?
Cheers
Rowan

**Comment by tcql** [comment]
:+1: on putting together comprehensive packages for these and getting them pulled in to turf. Boolean polygon operation of all sorts are on the wishlist. Awhile back I sunk some time looking at [DE-9IM](https://en.wikipedia.org/wiki/DE-9IM) which is kind of the ultimate / most specific way of describing geometric relationships, but is pretty lacking on reference implementations. 

If we ever got DE-9IM off the ground, we could easily write wrappers for overlaps, touches, within, etc with all geometry types.

**Comment by rowanwins** [comment]
Hmmm just did a quick google for DE-9IM, does look like a good standard to adopt for this sort of stuff. I found this python package  from a guy I think you work with I think... perhaps we can have a crack at converting this to js and see where it leads....
https://pypi.python.org/pypi/de9im/0.1
